#!/bin/bash


sudo ip link add dev vcan0 type vcan
sudo ip link add dev vcan1 type vcan
sudo ifconfig vcan0 up
sudo ifconfig vcan1 up

touch output.log
nc -l -u 5004 > output.log &
cangen vcan1 -g 2000 -I 42B -D 5643414E31202020 -L 8 &
cangen vcan0 -g 2000 -I 42A -D 5643414E30202020 -L 8 &

sleep 10

killall cangen
killall nc

cat output.log
#rm output.log
